/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as CardapioRouteImport } from './routes/cardapio'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReservaRouteImport } from './routes/reserva'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as ApiAdminRouteImport } from './routes/api/admin'
import { Route as ApiCardapioRouteImport } from './routes/api/cardapio'
import { Route as ApiCsrfRouteImport } from './routes/api/csrf'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiReservasRouteImport } from './routes/api/reservas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioRoute = CardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaRoute = ReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardapioRoute = ApiCardapioRouteImport.update({
  id: '/api/cardapio',
  path: '/api/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCsrfRoute = ApiCsrfRouteImport.update({
  id: '/api/csrf',
  path: '/api/csrf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReservasRoute = ApiReservasRouteImport.update({
  id: '/api/reservas',
  path: '/api/reservas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/cardapio': typeof CardapioRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/reserva': typeof ReservaRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/cardapio': typeof ApiCardapioRoute
  '/api/csrf': typeof ApiCsrfRoute
  '/api/login': typeof ApiLoginRoute
  '/api/reservas': typeof ApiReservasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cardapio': typeof CardapioRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/reserva': typeof ReservaRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/cardapio': typeof ApiCardapioRoute
  '/api/csrf': typeof ApiCsrfRoute
  '/api/login': typeof ApiLoginRoute
  '/api/reservas': typeof ApiReservasRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/cardapio': typeof CardapioRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/reserva': typeof ReservaRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/cardapio': typeof ApiCardapioRoute
  '/api/csrf': typeof ApiCsrfRoute
  '/api/login': typeof ApiLoginRoute
  '/api/reservas': typeof ApiReservasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/cardapio'
    | '/contato'
    | '/login'
    | '/reserva'
    | '/admin/agenda'
    | '/admin/cardapio'
    | '/admin/reservas'
    | '/api/admin'
    | '/api/cardapio'
    | '/api/csrf'
    | '/api/login'
    | '/api/reservas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cardapio'
    | '/contato'
    | '/login'
    | '/reserva'
    | '/admin/agenda'
    | '/admin/cardapio'
    | '/admin/reservas'
    | '/api/admin'
    | '/api/cardapio'
    | '/api/csrf'
    | '/api/login'
    | '/api/reservas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/cardapio'
    | '/contato'
    | '/login'
    | '/reserva'
    | '/admin/agenda'
    | '/admin/cardapio'
    | '/admin/reservas'
    | '/api/admin'
    | '/api/cardapio'
    | '/api/csrf'
    | '/api/login'
    | '/api/reservas'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  CardapioRoute: typeof CardapioRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  ReservaRoute: typeof ReservaRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiCardapioRoute: typeof ApiCardapioRoute
  ApiCsrfRoute: typeof ApiCsrfRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiReservasRoute: typeof ApiReservasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio': {
      id: '/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof CardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva': {
      id: '/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof ReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cardapio': {
      id: '/api/cardapio'
      path: '/api/cardapio'
      fullPath: '/api/cardapio'
      preLoaderRoute: typeof ApiCardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csrf': {
      id: '/api/csrf'
      path: '/api/csrf'
      fullPath: '/api/csrf'
      preLoaderRoute: typeof ApiCsrfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reservas': {
      id: '/api/reservas'
      path: '/api/reservas'
      fullPath: '/api/reservas'
      preLoaderRoute: typeof ApiReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminCardapioRoute: AdminCardapioRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendaRoute: AgendaRoute,
  CardapioRoute: CardapioRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  ReservaRoute: ReservaRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiCardapioRoute: ApiCardapioRoute,
  ApiCsrfRoute: ApiCsrfRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiReservasRoute: ApiReservasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
